# Camera settings
CAMERA_WIDTH = 640
CAMERA_HEIGHT = 480
CAMERA_FPS = 30
TARGET_FPS = 30
FRAME_INTERVAL = 1/TARGET_FPS
FRAME_SKIP = 2
MIN_FRAME_INTERVAL = 0.02
QUEUE_SIZE = 1

# GPU settings
USE_CUDA = True
CUDA_BENCHMARK = True
CUDA_ENABLED = True

# Model settings
CONFIDENCE_THRESHOLD = 0.25
IOU_THRESHOLD = 0.45

# Display settings
UPDATE_INTERVAL = 16  # ~60 FPS
STATUS_UPDATE_INTERVAL = 30  # Update status every 30 frames

# Performance thresholds
MAX_CPU_USAGE = 90
MAX_MEMORY_USAGE = 85
MAX_GPU_USAGE = 95

# Buffer settings
MAX_QUEUE_SIZE = 2
PROCESS_TIMEOUT = 0.1